spring:
  application:
    name: ai-agent
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: Qwen/Qwen3-8B
        base-url: https://api.siliconflow.cn
        completions-path: /v1/chat/completions
      embedding:
        options:
          model: qwen3-embedding:8b # dimensions: 4096
        base-url: http://localhost:11434
        embeddings-path: /v1/embeddings
        api-key: ollama
    chat:
      memory:
        repository:
          jdbc:
            platform: postgresql
            initialize-schema: always
    vectorstore:
      milvus:
        client:
          host: localhost
          port: 19530
        collection-name: ai_agent_collection
        embedding-dimension: 4096
        index-type: ivf_flat
        metric-type: cosine
        initialize-schema: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?ssl=false
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
server:
  port: 8080
  servlet:
    context-path: /api

# springdoc-openapi configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.mercemay.aiagent.controller

# knife4j config
knife4j:
  enable: true
  setting:
    language: zh_cn