package com.mercemay.aiagent.agent;

import cn.hutool.core.util.StrUtil;
import com.mercemay.aiagent.agent.model.AgentState;
import lombok.Data;
import lombok.extern.slf4j.Slf4j;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.messages.Message;
import org.springframework.ai.chat.messages.UserMessage;
import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CompletableFuture;


/**
 * A base class for AI agents that can process user prompts and generate responses.
 */
@Data
@Slf4j
public abstract class BaseAgent {
    /**
     * The name of the agent.
     */
    private String name;

    /**
     * The prompt that defines the agent's behavior and context.
     */
    private String systemPrompt;
    private String nextStepPrompt;

    /**
     * The current state of the agent.
     */
    private AgentState state = AgentState.IDLE;

    /**
     * The maximum number of iterations the agent can perform.
     */
    private int maxIterations = 10;
    private int currentIteration = 0;

    /**
     * The maximum number of consecutive identical outputs allowed before stopping.
     */
    private int maxConsecutiveLoops = 3;

    /**
     * The ChatClient used for communication.
     */
    private ChatClient chatClient;


    /**
     * The conversation history of messages exchanged with the agent.
     */
    private List<Message> messageList = new ArrayList<>();

    /**
     * Executes the agent's logic based on the provided user prompt.
     *
     * @param userPrompt The prompt provided by the user to guide the agent's actions.
     * @return The final response generated by the agent after processing the user prompt.
     */
    public String run(String userPrompt) {
        if (this.state != AgentState.IDLE) {
            throw new RuntimeException("Agent is already running");
        }
        if (StrUtil.isBlank(userPrompt)) {
            throw new RuntimeException("User prompt cannot be empty");
        }
        // Set agent state to PROCESSING
        this.state = AgentState.PROCESSING;
        // Add user prompt to message list
        messageList.add(new UserMessage(userPrompt));
        // Initialize step output list
        List<String> stepOutputList = new ArrayList<>();
        String lastStepOutput = null;
        int consecutiveLoopCount = 0;
        try {
            for (currentIteration = 1; currentIteration <= maxIterations && this.state != AgentState.COMPLETED; currentIteration++) {
                log.info("Agent '{}' - Iteration {}/{}", this.name, currentIteration, maxIterations);
                String stepOutput = this.step();

                // Loop detection
                if (stepOutput != null && stepOutput.equals(lastStepOutput)) {
                    consecutiveLoopCount++;
                    if (consecutiveLoopCount >= maxConsecutiveLoops) {
                        String loopMsg = String.format("Terminating due to consecutive identical output loop detection (%d times).", consecutiveLoopCount);
                        log.warn(loopMsg);
                        stepOutputList.add(loopMsg);
                        this.state = AgentState.COMPLETED;
                        break;
                    }
                } else {
                    consecutiveLoopCount = 0;
                }
                lastStepOutput = stepOutput;

                stepOutputList.add("Step " + currentIteration + " Output: " + stepOutput);
            }
            if (currentIteration > maxIterations) {
                this.state = AgentState.COMPLETED;
                log.info("Agent '{}' reached maximum iterations. Marking as COMPLETED.", this.name);
                stepOutputList.add("Termination: Reached maximum iterations.");
            }
            return String.join("\n", stepOutputList);
        } catch (Exception e) {
            this.state = AgentState.ERROR;
            log.error("Error occurred while running agent: ", e);
            return "Error: " + e.getMessage();
        } finally {
            this.cleanUp();
        }
    }

    /**
     * Executes the agent's logic in a streaming manner based on the provided user prompt.
     *
     * @param userPrompt The prompt provided by the user to guide the agent's actions.
     * @return An SseEmitter that streams the agent's responses as they are generated.
     */
    public SseEmitter runStream(String userPrompt) {
        SseEmitter sseEmitter = new SseEmitter(10 * 60 * 1000L); // 10 minutes timeout
        // Start asynchronous execution
        CompletableFuture.runAsync(() -> {
            try {
                if (this.state != AgentState.IDLE) {
                    sseEmitter.send("Error: Agent is already running");
                    sseEmitter.complete();
                    return;
                }
                if (StrUtil.isBlank(userPrompt)) {
                    sseEmitter.send("Error: User prompt cannot be empty");
                    sseEmitter.complete();
                    return;
                }
            } catch (Exception e) {
                sseEmitter.completeWithError(e);
            }
            // Set agent state to PROCESSING
            this.state = AgentState.PROCESSING;
            // Add user prompt to message list
            messageList.add(new UserMessage(userPrompt));
            // Initialize step output list
            List<String> stepOutputList = new ArrayList<>();
            String lastStepOutput = null;
            int consecutiveLoopCount = 0;
            try {
                for (currentIteration = 1; currentIteration <= maxIterations && this.state != AgentState.COMPLETED; currentIteration++) {
                    log.info("Agent '{}' - Iteration {}/{}", this.name, currentIteration, maxIterations);
                    String stepOutput = this.step();

                    // Loop detection
                    if (stepOutput != null && stepOutput.equals(lastStepOutput)) {
                        consecutiveLoopCount++;
                        if (consecutiveLoopCount >= maxConsecutiveLoops) {
                            String loopMsg = String.format("Terminating due to consecutive identical output loop detection (%d times).", consecutiveLoopCount);
                            log.warn(loopMsg);
                            sseEmitter.send(loopMsg);
                            this.state = AgentState.COMPLETED;
                            break;
                        }
                    } else {
                        consecutiveLoopCount = 0;
                    }
                    lastStepOutput = stepOutput;

                    String outputMessage = "Step " + currentIteration + " Output: " + stepOutput;
                    stepOutputList.add(outputMessage);
                    sseEmitter.send(outputMessage);
                }
                if (currentIteration > maxIterations) {
                    this.state = AgentState.COMPLETED;
                    log.info("Agent '{}' reached maximum iterations. Marking as COMPLETED.", this.name);
                    String terminationMessage = "Termination: Reached maximum iterations.";
                    stepOutputList.add(terminationMessage);
                    sseEmitter.send(terminationMessage);
                }
                sseEmitter.complete();
            } catch (Exception e) {
                this.state = AgentState.ERROR;
                log.error("Error occurred while running agent: ", e);
                try {
                    sseEmitter.send("Error: " + e.getMessage());
                    sseEmitter.complete();
                } catch (Exception sendEx) {
                    log.error("Error sending error message via SseEmitter: ", sendEx);
                    sseEmitter.completeWithError(sendEx);
                }
            } finally {
                this.cleanUp();
            }
        });

        sseEmitter.onTimeout(() -> {
            this.state = AgentState.ERROR;
            log.error("SseEmitter timed out for agent '{}'", this.name);
            this.cleanUp();
        });
        sseEmitter.onCompletion(() -> {
            if (this.state == AgentState.PROCESSING) {
                this.state = AgentState.COMPLETED;
            }
            log.info("SseEmitter completed for agent '{}'", this.name);
            this.cleanUp();
        });
        return sseEmitter;
    }

    /**
     * Performs a single step of the agent's logic.
     *
     * @return The result of the step execution.
     */
    public abstract String step();

    /**
     * Cleans up resources or resets the agent's state after execution.
     */
    protected void cleanUp() {
        log.info("Cleaning up agent '{}'", this.name);
        // Reset current iteration
        this.currentIteration = 0;
        // Clear message list
        this.messageList.clear();
        // Reset state to IDLE
        this.state = AgentState.IDLE;
    }

    public void setStateAsCompleted() {
        this.state = AgentState.COMPLETED;
    }
}
